[package]
name = "bitcoin-rpc-test"
version = "0.1.0"
edition = "2021"

[dependencies]
#bitcoincore-rpc = "0.19.0"
bitcoincore-rpc = { path = "../client" }
bitcoincore-rpc-json = { path = "../json" }
env_logger = "0.11"
log = "0.4"